version: '3.8'
services:

  bookmarks-db:
    image: postgres:16.0-alpine
    container_name: bookmarks-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bookmarks-go:
    build: .
    ports:
      - "18080:8080"
    restart: unless-stopped
    depends_on:
      - bookmarks-db
    environment:
      DB_HOST: bookmarks-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_RUN_MIGRATIONS: "true"
      DB_MIGRATIONS_LOCATION: "file:///migrations"